# Generated by Django 6.0.6 on 2026-06-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=300)),
                ('short_name', models.CharField(db_index=True, max_length=20, unique=True)),
                ('location_city', models.CharField(blank=True, max_length=100)),
                ('location_state', models.CharField(default='Tamil Nadu', max_length=100)),
                ('university_affiliation', models.CharField(blank=True, max_length=200)),
                ('college_type', models.CharField(choices=[('autonomous', 'Autonomous'), ('affiliated', 'Affiliated'), ('government', 'Government Aided'), ('private', 'Private Unaided')], default='affiliated', max_length=20)),
                ('accreditation', models.CharField(blank=True, max_length=100)),
                ('established', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('courses_offered', models.JSONField(blank=True, default=list)),
                ('primary_image', models.ImageField(blank=True, null=True, upload_to='colleges/images/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='colleges/banners/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'College',
                'verbose_name_plural': 'Colleges',
                'ordering': ['college_name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate')], default='Undergraduate', max_length=20)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='📚', max_length=10)),
                ('students', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('colleges', models.ManyToManyField(blank=True, related_name='course_set', to='colleges.college')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['category', 'title'],
            },
        ),
    ]
