# Generated by Django 6.0.4 on 2026-06-24 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['category', 'course_name'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='colleges',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.RemoveField(
            model_name='course',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
        migrations.AddField(
            model_name='course',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='degree_type',
            field=models.CharField(choices=[('ug', 'UG'), ('pg', 'PG'), ('diploma', 'Diploma'), ('phd', 'PhD')], db_index=True, default='ug', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
