# Generated by Django 6.0.6 on 2026-07-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_redesign_course_model_api_compatible'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, default='3 Years', max_length=50),
        ),
    ]
