# Generated by Django 6.0.6 on 2026-07-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='campus_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='college',
            name='college_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='college',
            name='facilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='college',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='college',
            name='why_choose_us',
            field=models.TextField(blank=True),
        ),
    ]
