# Generated by Django 6.0.6 on 2026-06-23 13:13

import applications.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(db_index=True, default=applications.models.application_id_default, max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('community', models.CharField(blank=True, max_length=50)),
                ('aadhar_number', models.CharField(blank=True, max_length=20)),
                ('father_name', models.CharField(blank=True, max_length=150)),
                ('father_mobile', models.CharField(blank=True, max_length=15)),
                ('mother_name', models.CharField(blank=True, max_length=150)),
                ('mother_mobile', models.CharField(blank=True, max_length=15)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=15)),
                ('tenth_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('twelfth_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('has_diploma', models.BooleanField(default=False)),
                ('diploma_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('has_ug', models.BooleanField(default=False)),
                ('ug_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('college_name', models.CharField(blank=True, max_length=300)),
                ('course_name', models.CharField(blank=True, max_length=200)),
                ('department_name', models.CharField(blank=True, max_length=200)),
                ('reference_name', models.CharField(blank=True, max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='applications/photos/')),
                ('tenth_marksheet', models.FileField(blank=True, null=True, upload_to='applications/docs/')),
                ('twelfth_marksheet', models.FileField(blank=True, null=True, upload_to='applications/docs/')),
                ('aadhar', models.FileField(blank=True, null=True, upload_to='applications/docs/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('counselor_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='colleges.college')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
