# Generated by Django 6.0.4 on 2026-06-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
