# Generated by Django 6.0.4 on 2026-06-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='degree_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
